name: poultry_classify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.2.14

  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.9.0
  http: ^1.0.0
  async: ^2.11.0
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  image: assets/splash.png
  color: "#513064"
  android: true
  ios: true
  fullscreen: true
  android_gravity: fill
  ios_content_mode: fill


  android_12:
    color: "#513064"
    image: assets/splash.png
    fullscreen: true
    android_gravity: fill
    ios_content_mode: fill
